# Base image versions
FROM python:3.8-alpine

# install lxml
RUN apk add --update --no-cache g++ gcc libxslt-dev

# copy indevidual file, ensure that each step’s build cache is only invalidated 
COPY ./app/requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt
ADD ./app /app

# Wait for CMD to exit, reap zombies and perform signal forwarding
# ENTRYPOINT ["/sbin/tini", "--"]
CMD ["python", "-u", "main.py"]